version: '3.7'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      [ "5432:5432" ]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab_5